package controllers;

public enum CommandName {
	
	GO_TO_BASE_PAGE, GO_TO_ERROR_PAGE,GO_TO_23279,DO_WRITE,GO_TO_DO_WRITE_PAGE,SHOW_5_IN_JOURNEY,GO_TO_WIRES500,DO_WRITES500,
	SHOW_WRITES_IN_JOURNEYS500,SHOW_WRITES_IN_JOURNEYS500_2,SHOW_JOURNEY_S500_ID	
	
}
