package controllers;

public enum CommandName {
	
	GO_TO_BASE_PAGE, GO_TO_ERROR_PAGE,GO_TO_23279,DO_WRITE,GO_TO_DO_WRITE_PAGE	
	

	/*
	 * GO_TO_BASE_PAGE, GO_TO_LOGINATION_PAGE, GO_TO_REGISTRATION_PAGE,
	 * DO_REGISTRATION, GO_TO_NEWS_LIST, GO_TO_VIEW_NEWS, GO_TO_MANAGER_PAGE,
	 * DO_ADD_NEWS, GO_TO_ADD_NEWSPAGE,
	 * 
	 * DO_SIGN_IN, DO_SIGN_OUT, DO_LOCAL_CHANGE, GO_TO_ERROR_PAGE
	 */
}
